/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistProfile {
  'bio' : string,
  'externalLinks' : Array<string>,
  'donationsEnabled' : boolean,
  'displayName' : string,
  'stripeAccessToken' : [] | [string],
  'avatar' : ExternalBlob,
}
export interface DonatePaymentInput {
  'stripeAccessToken' : string,
  'donorName' : string,
  'artistId' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'recipientId' : string,
}
export interface DonatePaymentOutput {
  'message' : string,
  'paymentId' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'donor' : string,
  'recipientId' : string,
}
export type ExternalBlob = Uint8Array;
export type MediaCategory = { 'video' : null } |
  { 'liveSession' : null } |
  { 'recording' : null };
export interface MediaItem {
  'id' : string,
  'title' : string,
  'created' : bigint,
  'file' : ExternalBlob,
  'tags' : Array<string>,
  'artistId' : Principal,
  'description' : string,
  'category' : MediaCategory,
}
export interface MediaItemDTO {
  'id' : string,
  'title' : string,
  'created' : bigint,
  'file' : ExternalBlob,
  'tags' : Array<string>,
  'description' : string,
  'category' : MediaCategory,
  'artist' : ArtistProfile,
  'totalDonations' : bigint,
}
export interface MediaItemInput {
  'title' : string,
  'created' : bigint,
  'file' : ExternalBlob,
  'tags' : Array<string>,
  'artistId' : Principal,
  'description' : string,
  'category' : MediaCategory,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStripeAccessToken' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteMediaItem' : ActorMethod<[string], undefined>,
  'donate' : ActorMethod<[DonatePaymentInput], DonatePaymentOutput>,
  'getAllMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'getArtist' : ActorMethod<[Principal], [] | [ArtistProfile]>,
  'getCallerArtist' : ActorMethod<[], [] | [ArtistProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMediaItem' : ActorMethod<[string], [] | [MediaItemDTO]>,
  'getMediaItemCountByCategory' : ActorMethod<
    [Principal, MediaCategory],
    bigint
  >,
  'getMediaItemsByArtist' : ActorMethod<[Principal], Array<MediaItem>>,
  'getMediaItemsByCategory' : ActorMethod<[MediaCategory], Array<MediaItem>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isDonationsEnabled' : ActorMethod<[Principal], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'onboardArtist' : ActorMethod<[ArtistProfile], undefined>,
  'revokeStripeAccessToken' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArtist' : ActorMethod<[ArtistProfile], undefined>,
  'uploadMediaItem' : ActorMethod<[MediaItemInput], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];