/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const DonatePaymentInput = IDL.Record({
  'stripeAccessToken' : IDL.Text,
  'donorName' : IDL.Text,
  'artistId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'recipientId' : IDL.Text,
});
export const DonatePaymentOutput = IDL.Record({
  'message' : IDL.Text,
  'paymentId' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'donor' : IDL.Text,
  'recipientId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaCategory = IDL.Variant({
  'video' : IDL.Null,
  'liveSession' : IDL.Null,
  'recording' : IDL.Null,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'created' : IDL.Int,
  'file' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'artistId' : IDL.Principal,
  'description' : IDL.Text,
  'category' : MediaCategory,
});
export const ArtistProfile = IDL.Record({
  'bio' : IDL.Text,
  'externalLinks' : IDL.Vec(IDL.Text),
  'donationsEnabled' : IDL.Bool,
  'displayName' : IDL.Text,
  'stripeAccessToken' : IDL.Opt(IDL.Text),
  'avatar' : ExternalBlob,
});
export const MediaItemDTO = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'created' : IDL.Int,
  'file' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : MediaCategory,
  'artist' : ArtistProfile,
  'totalDonations' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const MediaItemInput = IDL.Record({
  'title' : IDL.Text,
  'created' : IDL.Int,
  'file' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'artistId' : IDL.Principal,
  'description' : IDL.Text,
  'category' : MediaCategory,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStripeAccessToken' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
  'donate' : IDL.Func([DonatePaymentInput], [DonatePaymentOutput], []),
  'getAllMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getArtist' : IDL.Func([IDL.Principal], [IDL.Opt(ArtistProfile)], ['query']),
  'getCallerArtist' : IDL.Func([], [IDL.Opt(ArtistProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMediaItem' : IDL.Func([IDL.Text], [IDL.Opt(MediaItemDTO)], ['query']),
  'getMediaItemCountByCategory' : IDL.Func(
      [IDL.Principal, MediaCategory],
      [IDL.Nat],
      ['query'],
    ),
  'getMediaItemsByArtist' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'getMediaItemsByCategory' : IDL.Func(
      [MediaCategory],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isDonationsEnabled' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'onboardArtist' : IDL.Func([ArtistProfile], [], []),
  'revokeStripeAccessToken' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArtist' : IDL.Func([ArtistProfile], [], []),
  'uploadMediaItem' : IDL.Func([MediaItemInput], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const DonatePaymentInput = IDL.Record({
    'stripeAccessToken' : IDL.Text,
    'donorName' : IDL.Text,
    'artistId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'recipientId' : IDL.Text,
  });
  const DonatePaymentOutput = IDL.Record({
    'message' : IDL.Text,
    'paymentId' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'donor' : IDL.Text,
    'recipientId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaCategory = IDL.Variant({
    'video' : IDL.Null,
    'liveSession' : IDL.Null,
    'recording' : IDL.Null,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'created' : IDL.Int,
    'file' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'artistId' : IDL.Principal,
    'description' : IDL.Text,
    'category' : MediaCategory,
  });
  const ArtistProfile = IDL.Record({
    'bio' : IDL.Text,
    'externalLinks' : IDL.Vec(IDL.Text),
    'donationsEnabled' : IDL.Bool,
    'displayName' : IDL.Text,
    'stripeAccessToken' : IDL.Opt(IDL.Text),
    'avatar' : ExternalBlob,
  });
  const MediaItemDTO = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'created' : IDL.Int,
    'file' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : MediaCategory,
    'artist' : ArtistProfile,
    'totalDonations' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const MediaItemInput = IDL.Record({
    'title' : IDL.Text,
    'created' : IDL.Int,
    'file' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'artistId' : IDL.Principal,
    'description' : IDL.Text,
    'category' : MediaCategory,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStripeAccessToken' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
    'donate' : IDL.Func([DonatePaymentInput], [DonatePaymentOutput], []),
    'getAllMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getArtist' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ArtistProfile)],
        ['query'],
      ),
    'getCallerArtist' : IDL.Func([], [IDL.Opt(ArtistProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMediaItem' : IDL.Func([IDL.Text], [IDL.Opt(MediaItemDTO)], ['query']),
    'getMediaItemCountByCategory' : IDL.Func(
        [IDL.Principal, MediaCategory],
        [IDL.Nat],
        ['query'],
      ),
    'getMediaItemsByArtist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getMediaItemsByCategory' : IDL.Func(
        [MediaCategory],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isDonationsEnabled' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'onboardArtist' : IDL.Func([ArtistProfile], [], []),
    'revokeStripeAccessToken' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArtist' : IDL.Func([ArtistProfile], [], []),
    'uploadMediaItem' : IDL.Func([MediaItemInput], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };